// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
)

type Customer struct {
	ID      int32
	Name    string
	Email   string
	Address sql.NullString
}

type Order struct {
	ID         int32
	CustomerID int32
	OrderDate  sql.NullTime
	Status     string
}

type OrderItem struct {
	ID        int32
	OrderID   int32
	ProductID int32
	Quantity  int32
}

type Product struct {
	ID          int32
	Name        string
	Description sql.NullString
	Price       string
}

type Stock struct {
	ID                int32
	ProductID         int32
	AvailableQuantity int32
}
